-- MySQL Script generated by MySQL Workbench
-- Sat Nov 25 20:18:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema chirper
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chirper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chirper` DEFAULT CHARACTER SET utf8 ;
USE `chirper` ;

-- -----------------------------------------------------
-- Table `chirper`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chirper`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `pswd_hash` VARCHAR(256) NOT NULL,
  `pswd_token` VARCHAR(256) NULL,
  `email_token` VARCHAR(256) NULL,
  `score` DOUBLE NULL,
  `verified` TINYINT NULL DEFAULT 0,
  `fbId` VARCHAR(25) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `fbId_UNIQUE` (`fbId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chirper`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chirper`.`Post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `content` VARCHAR(256) NULL,
  `attach` VARCHAR(256) NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `score` DOUBLE NOT NULL DEFAULT 1,
  `latitude` DOUBLE NOT NULL DEFAULT 0,
  `longitude` DOUBLE NOT NULL DEFAULT 0,
  PRIMARY KEY (`idPost`),
  UNIQUE INDEX `idPost_UNIQUE` (`idPost` ASC),
  INDEX `user_idx` (`user` ASC),
  CONSTRAINT `user`
    FOREIGN KEY (`user`)
    REFERENCES `chirper`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chirper`.`Lit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chirper`.`Lit` (
  `user` INT NOT NULL,
  `post` INT NOT NULL,
  PRIMARY KEY (`user`, `post`),
  INDEX `post_idx` (`post` ASC),
  CONSTRAINT `users`
    FOREIGN KEY (`user`)
    REFERENCES `chirper`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `posts`
    FOREIGN KEY (`post`)
    REFERENCES `chirper`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `chirper` ;

-- -----------------------------------------------------
-- function distancia
-- -----------------------------------------------------

DELIMITER $$
USE `chirper`$$
CREATE FUNCTION `distancia` (lat1 DOUBLE, lon1 DOUBLE, lat2 DOUBLE, lon2 DOUBLE) RETURNS DOUBLE
BEGIN
RETURN  6371*acos(cos(radians(lat1))*cos(radians(lat2))*cos(radians(lon2)-radians(lon1))+sin(radians(lat1))*sin(radians(lat2)));
END;$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
